const doctors_list = ref([
  {
    name: "Lionel Messi",
    email: "messi@gmail.com",
    phone: "+8801700123456",
    address: "Mirpur, Dhaka",
    id: "square",
  },
  {
    name: "Sergio Busquets",
    email: "busi@gmail.com",
    phone: "+8801700125555",
    address: "Mirpur, Dhaka",
    id: "square",
  },
  {
    name: "Pep Guardiola",
    email: "pep@gmail.com",
    phone: "+8801700123687",
    address: "Mirpur, Dhaka",
    id: "square",
  },
  {
    name: "Ronald Koeman",
    email: "koeman@gmail.com",
    phone: "+8801700123687",
    address: "Mirpur, Dhaka",
    id: "square",
  },
  {
    name: "Ronald Araujo",
    email: "araujo@gmail.com",
    phone: "+8801700123687",
    address: "Mirpur, Dhaka",
    id: "square",
  },
  {
    name: "Emi Martinez",
    email: "martinez@gmail.com",
    phone: "+8801700123111",
    address: "Mirpur-12, Dhaka",
    id: "popular",
  },
  {
    name: "Di Maria",
    email: "maria@gmail.com",
    phone: "+8801700444456",
    address: "Mirpur-12, Dhaka",
    id: "popular",
  },
  {
    name: "Joules Kounde",
    email: "kounde@gmail.com",
    phone: "+8801700444456",
    address: "Mirpur-11, Dhaka",
    id: "popular",
  },
  {
    name: "Di Stefano",
    email: "di@gmail.com",
    phone: "+8801700444456",
    address: "Mirpur-10, Dhaka",
    id: "popular",
  },
  {
    name: "Luis Suarez",
    email: "suarez@gmail.com",
    phone: "+8801700444456",
    address: "Mirpur-12, Dhaka",
    id: "popular",
  },
  {
    name: "Luis Suarez",
    email: "suarez@gmail.com",
    phone: "+8801700444456",
    address: "Mirpur-12, Dhaka",
    id: "labaid",
  },
  {
    name: "Luis Enrique",
    email: "suarez@gmail.com",
    phone: "+8801700444456",
    address: "Uttara, Dhaka",
    id: "labaid",
  },
  {
    name: "Luis Menotti",
    email: "menotti@gmail.com",
    phone: "+8801700444456",
    address: "Uttara, Dhaka",
    id: "labaid",
  },
  {
    name: "Diego Maradona",
    email: "d10@gmail.com",
    phone: "+8801700444456",
    address: "Mirpur-10, Dhaka",
    id: "labaid",
  },
  {
    name: "Johan Cruyff",
    email: "johan@gmail.com",
    phone: "+8801700444456",
    address: "Mirpur-12, Dhaka",
    id: "labaid",
  },
  {
    name: "Luis Suarez",
    email: "suarez@gmail.com",
    phone: "+8801700444456",
    address: "Mirpur-12, Dhaka",
    id: "ibnsina",
  },
  {
    name: "Luis Enrique",
    email: "suarez@gmail.com",
    phone: "+8801700444456",
    address: "Uttara, Dhaka",
    id: "ibnsina",
  },
  {
    name: "Luis Menotti",
    email: "menotti@gmail.com",
    phone: "+8801700444456",
    address: "Uttara, Dhaka",
    id: "ibnsina",
  },
  {
    name: "Diego Maradona",
    email: "d10@gmail.com",
    phone: "+8801700444456",
    address: "Mirpur-10, Dhaka",
    id: "ibnsina",
  },
  {
    name: "Johan Cruyff",
    email: "johan@gmail.com",
    phone: "+8801700444456",
    address: "Mirpur-12, Dhaka",
    id: "ibnsina",
  },
  {
    name: "Lionel Messi",
    email: "messi@gmail.com",
    phone: "+8801700123456",
    address: "Mirpur, Dhaka",
    id: "birdem",
  },
  {
    name: "Sergio Busquets",
    email: "busi@gmail.com",
    phone: "+8801700125555",
    address: "Mirpur, Dhaka",
    id: "birdem",
  },
  {
    name: "Pep Guardiola",
    email: "pep@gmail.com",
    phone: "+8801700123687",
    address: "Mirpur, Dhaka",
    id: "birdem",
  },
  {
    name: "Ronald Koeman",
    email: "koeman@gmail.com",
    phone: "+8801700123687",
    address: "Mirpur, Dhaka",
    id: "birdem",
  },
  {
    name: "Ronald Araujo",
    email: "araujo@gmail.com",
    phone: "+8801700123687",
    address: "Mirpur, Dhaka",
    id: "birdem",
  },
]);

export const useDoctor = () => {
  return doctors_list;
};
